on: push

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
          - x86_64-unknown-linux-musl
          - arm-unknown-linux-gnueabihf
          - arm-unknown-linux-musleabihf

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
          components: rustfmt, clippy

      - uses: actions-rs/cargo@v1
        name: Release Build
        with:
          command: build
          args: --release

      - uses: actions-rs/cargo@v1
        name: Run Tests
        with:
          command: test

      - uses: actions-rs/cargo@v1
        name: Check Formatting
        with:
          command: fmt
          args: --all -- --check

      # - uses: actions-rs/cargo@v1
      #   with:
      #     command: clippy
      #     args: -- -D warnings

      - uses: actions/upload-artifact@v3
        with:
          name: someipsd-explorer-${{ matrix.target }}
          path: target
          retention-days: 5
